version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: douglasq/nginx
    container_name: nginx
    ports: 
      - "80:80"
    networks: 
      - prod-network
    depends_on:
      - "node1"
      - "node2"
      - "mongodb"
  mongodb:
    image: mongo
    networks: 
      - prod-network
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books-1
    networks:
      - prod-network
    ports: 
      - "3000"
    depends_on: 
      - "mongodb"
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: douglasq/alura-books
    container_name: alura-books-2
    networks:
      - prod-network
    ports: 
      - "3000"
    depends_on: 
      - "mongodb"
networks: 
  prod-network:
    driver: bridge
